'use client'

import { Video, Share2, BarChart3, CheckCircle } from 'lucide-react'

interface BrandSyncDashboardProps {
  brandData: any
}

export default function BrandSyncDashboard({ brandData }: BrandSyncDashboardProps) {
  return (
    <div className="min-h-screen p-6">
      <div className="max-w-7xl mx-auto">
        {/* Success Banner */}
        <div className="bg-green-50 border-2 border-green-200 rounded-2xl p-6 mb-8 flex items-center gap-4">
          <CheckCircle className="w-12 h-12 text-green-600" />
          <div>
            <h2 className="text-2xl font-bold text-green-900">BrandSync Complete! 🎉</h2>
            <p className="text-green-700">Your brand has been analyzed and synced to our platform.</p>
          </div>
        </div>

        {/* Next Steps */}
        <div className="mb-8">
          <h3 className="text-3xl font-bold mb-6">What's Next?</h3>
          <div className="grid md:grid-cols-3 gap-6">
            <AgentCard
              icon={<Video className="w-8 h-8" />}
              title="Content Creator Agent"
              description="Generate brand-consistent videos, graphics, and captions automatically"
              status="Ready"
              action="Start Creating"
              color="purple"
            />
            <AgentCard
              icon={<Share2 className="w-8 h-8" />}
              title="Social Media Agent"
              description="Schedule and post content across all your social media platforms"
              status="Ready"
              action="Connect Accounts"
              color="blue"
            />
            <AgentCard
              icon={<BarChart3 className="w-8 h-8" />}
              title="Analytics Agent"
              description="Track performance and optimize your content strategy with AI"
              status="Coming Soon"
              action="Learn More"
              color="green"
            />
          </div>
        </div>

        {/* Brand Info Preview */}
        <div className="bg-white rounded-2xl shadow-xl p-8">
          <h3 className="text-2xl font-bold mb-6">Your Brand Profile</h3>
          <div className="prose max-w-none">
            <p className="text-gray-600 mb-4">
              We've analyzed your brand and stored the following information in our database:
            </p>
            <ul className="space-y-2 text-gray-700">
              <li>✅ Brand identity and logo</li>
              <li>✅ Color palette and fonts</li>
              <li>✅ Company vibe and tone</li>
              <li>✅ Target audience profile</li>
              <li>✅ Industry and positioning</li>
            </ul>
            <div className="mt-6 p-4 bg-purple-50 rounded-xl">
              <p className="text-sm text-purple-900">
                💡 <strong>Pro Tip:</strong> All content generated by our agents will automatically align with your brand identity!
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

function AgentCard({
  icon,
  title,
  description,
  status,
  action,
  color,
}: {
  icon: React.ReactNode
  title: string
  description: string
  status: string
  action: string
  color: string
}) {
  const colorClasses = {
    purple: 'from-purple-500 to-purple-700',
    blue: 'from-blue-500 to-blue-700',
    green: 'from-green-500 to-green-700',
  }

  return (
    <div className="bg-white rounded-2xl shadow-lg p-6 hover:shadow-2xl transition-all transform hover:-translate-y-1">
      <div className={`bg-gradient-to-br ${colorClasses[color as keyof typeof colorClasses]} text-white w-16 h-16 rounded-xl flex items-center justify-center mb-4`}>
        {icon}
      </div>
      <div className="mb-4">
        <div className="flex items-center justify-between mb-2">
          <h4 className="text-xl font-bold">{title}</h4>
          <span className="text-xs px-3 py-1 bg-green-100 text-green-700 rounded-full font-semibold">
            {status}
          </span>
        </div>
        <p className="text-gray-600 text-sm">{description}</p>
      </div>
      <button className="w-full gradient-bg text-white py-3 rounded-xl font-semibold hover:shadow-lg transition-all">
        {action}
      </button>
    </div>
  )
}
